package com.avitoohband.nutrun

internal data class ExerciseSeed(val id: String, val name: String, val category: String, val primaryMuscles: String, val secondaryMuscles: String = "", val instructions: String, val safetyNote: String, val defaultSets: Int = 3, val defaultReps: Int = 10, val defaultWeightKg: Double? = null, val defaultDurationMinutes: Int? = null, val defaultDistanceKm: Double? = null)

private fun slug(name: String) = name.lowercase().replace(Regex("[^a-z0-9]+"), "-").trim('-')
private fun seeds(category: String, names: String) = names.split("|").map { name -> ExerciseSeed(slug(name), name, category, category, instructions = "Use a controlled range of motion and steady breathing.", safetyNote = "Stop if you feel sharp pain or cannot maintain good form.") }
internal val builtInExerciseSeeds =
    seeds("Free weights", "Dumbbell floor press|Dumbbell pullover|Dumbbell incline fly|Dumbbell front raise|Dumbbell lateral raise|Dumbbell rear delt row|Dumbbell sumo squat|Dumbbell step-back lunge|Dumbbell Romanian deadlift|Dumbbell split squat|Barbell good morning|Barbell hip bridge|Barbell reverse lunge|Barbell sumo deadlift|Barbell close-grip press|Barbell skull crusher|EZ-bar curl|Zottman curl|Incline dumbbell curl|Dumbbell wrist curl|Dumbbell reverse wrist curl|Kettlebell clean|Kettlebell snatch|Kettlebell front rack carry|Kettlebell Turkish get-up") +
    seeds("Machine", "Smith machine squat|Smith machine incline press|Machine row|Plate-loaded row|Seated leg press|Lying leg curl|Seated leg curl|Reverse hyperextension|Calf press machine|Seated calf raise|Machine preacher curl|Machine lateral raise|Glute drive machine|Back extension machine|Machine dip|Machine crunch|Machine pullover|Machine biceps curl|Machine triceps extension|Machine rear delt fly|Machine shoulder shrug|Machine hip thrust|Machine abduction kickback|Machine adduction press|Machine rotary torso") +
    seeds("Cable", "Cable chest press|Cable incline press|Cable crossover|Cable low row|Cable pullover|Cable biceps curl|Rope hammer curl|Cable reverse curl|Cable upright row|Cable rear delt fly|Cable front raise|Cable pull-through|Cable hip abduction|Cable hip adduction|Pallof press|Cable crunch|Cable reverse crunch|Cable single-arm row|Cable high row|Cable straight-arm pulldown|Cable kneeling lat pulldown|Cable shrug|Cable reverse fly|Cable external rotation|Cable internal rotation") +
    seeds("Calisthenics", "Pull up|Wide-grip pull up|Neutral-grip pull up|Tuck planche hold|Advanced tuck planche|Straddle planche progression|Planche lean|Pike push-up|Handstand push-up|Wall handstand hold|Muscle-up progression|Ring row|Archer push-up|Pseudo planche push-up|L-sit|Hanging leg raise|Toes to bar|Skin the cat|Tuck front lever|Advanced tuck front lever|Dragon flag progression|Human flag progression|Parallel bar dip|Typewriter pull up|Back lever tuck") +
    seeds("Rehabilitation", "Band external rotation|Band internal rotation|Shoulder isometric|Rehab wall slide|Scapular retraction|Prone Y raise|Prone T raise|Prone W raise|Quad set|Straight leg raise|Terminal knee extension|Heel slide|Rehab clamshell|Side-lying hip abduction|Rehab bridge|Eccentric calf raise|Tibialis raise|Ankle eversion band|Ankle inversion band|Single-leg balance|Heel-toe walk|Wrist flexion rehab|Wrist extension rehab|Median nerve glide|Pelvic tilt") +
    seeds("Home", "Chair squat|Wall push-up|Countertop push-up|Doorway row|Backpack row|Backpack deadlift|Backpack overhead press|Towel biceps curl|Chair triceps dip|Couch split squat|Stair step-up|Towel hamstring curl|Standing hip hinge|Wall calf raise|Floor snow angel|Home plank|Home side plank|Sit-up|Home reverse lunge")